config/routes.rb
TapeRepository::Application.routes.draw do
  root to: 'tapes#index'
  resources :tapes
  
  

end

app/models/tape.rb
class Tape < ActiveRecord::Base
  attr_accessible :description, :number
  
  validates :number, :description, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tapes_controller.rb
class TapesController < ApplicationController
  def index
    @tapes = Tape.find(:all, order: "number")
  end

  def new
    @title = "Add Tape"
    @tape = Tape.new
  end
  
  def show
    @tape = Tape.find(params[:id])   
    @title = "#{@tape.number} #{@tape.description}"
    @code = "tapes/#{@tape.number}.png"
  end
  
  def edit
    @tape = Tape.find(params[:id])
    @title = "Edit Tape #{@tape.number}"
  end
  
  def create
    @tape = Tape.new(params[:tape])
    if @tape.save
      redirect_to @tape, :flash => {:success => "New tape record created" }
    else
      render 'new'
    end
  end
  
  def update
    @tape = Tape.find(params[:id])
    if @tape.update_attributes(params[:tape])
      redirect_to @tape
    else
      redirect_to @tape, :flash => {:failure => "Unable to save edit" }
    end
  end
  
  def destroy
    @tape = Tape.find(params[:id])
    @tape.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
      base_title = "TETCO Tape Information Repository"
      if @title.nil?
        base_title
      else
        "#{base_title} | #{@title}"
      end
    end
    
    def logo
      logo = image_tag("logo.png", alt: "TETCO Tape Repository", class: "box")      
    end
    
    def code
      code = image_tag("#{@tape.number}.png")
    end
end

app/helpers/tapes_helper.rb
module TapesHelper

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to logo, root_path, id: "logo" %>
			<nav>
				<ul class="nav center">
					<li><%= link_to "INDEX", root_path %></li>
					<li><%= link_to "NEW", new_tape_path %></li>
				</ul>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/tapes/_form.html.erb
<%= form_for(@tape) do |f| %>
  <% if @tape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tape.errors.count, "error") %> prohibited this tape from being saved:</h2>

      <ul>
      <% @tape.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

		<div class="span5 offset1">
		  <div class="row">
		    <%= f.label 'Number' %>
		    <%= f.text_field :number %>
		  </div>
		  <div class="row">
		    <%= f.label 'Description' %>
		    <%= f.text_field :description %>
		  </div>
		  <div class="actions">
		    <%= f.submit %>
		  </div>
		<% end %>			
		</div>

app/views/tapes/edit.html.erb
<h1>Editing tape</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @tape %> |
<%= link_to 'Back', tapes_path %>

app/views/tapes/index.html.erb
<h2>Full Tape Inventory</h2>
<h4><%= link_to 'Enter New Tape', new_tape_path %></h4>
<table>
<% @tapes.each do |tape| %>
  <tr>
    <td><%= link_to "#{tape.number}", tape %></td>
		<td><%= "#{tape.description}" %></td>
    <td><%= link_to 'Edit', edit_tape_path(tape) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/tapes/new.html.erb
<h1>Tapes#new</h1>
<p>Find me in app/views/tapes/new.html.erb</p>

app/views/tapes/show.html.erb
<h1>
	<%= @tape.description %>
</h1>
<h3>
	Tape Number:
	<%= @tape.number %>
</h3>
<h3>
	<b>Code:</b><br />
	<%= link_to image_tag(@code), asset_path(@code) %>
</h3>

<%= link_to 'Edit', edit_tape_path(@tape) %> |
<%= link_to 'Delete', @tape, confirm: 'Are you sure?', method: :delete %> | 
<%= link_to 'Back', tapes_path %>